---
title: "Scraping and Analysis"
author: "Waleed Iftikhar and Sameer Swarup"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
library(tidyverse)
library(purrr)
library(survey)
library(forcats)
library(class)
library(readr)
```

###Scraping data from Wikipedia

```{r}
wikiurl <- "https://en.wikipedia.org/wiki/Ronaldo%E2%80%93Messi_rivalry#Club_statistics"
```

```{r}
wikipage <- read_html(wikiurl)
```

*Creating a dataset of club goals*
```{r}
tables.html <- html_nodes(wikipage,"table")
clgls <- html_table(tables.html[[5]], fill = TRUE) %>% as_tibble()
```

*Creating a dataset of Messi Club Goals.*
```{r}
messiclgls <- clgls  %>%
  select(X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,X11,X12)%>%
  slice(3:22)
messiclgls <- messiclgls %>%
  rename(Club = "X1", Season = "X2", LeagueApps = "X3", LeagueGoals = "X4", CupApps = "X5", CupGoals = "X6",EuropeApps = "X7", EuropeGoals = "X8",OtherApps = "X9", OtherGoals = "X10",TotalApps = "X11", TotalGoals = "X12" )
messiclgls <- messiclgls%>%
  slice(-(1:3))%>%
  slice(-17)
```

*Creating a dataset of Ronaldo Club Goals*

```{r}
crisclgls <- clgls  %>%
  select(X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,X11,X12)%>%
  slice(23:47)
crisclgls <- crisclgls %>%
  rename(Club = "X1", Season = "X2", LeagueApps = "X3", LeagueGoals = "X4", CupApps = "X5", CupGoals = "X6",EuropeApps = "X7", EuropeGoals = "X8",OtherApps = "X9", OtherGoals = "X10",TotalApps = "X11", TotalGoals = "X12" )
crisclgls <- crisclgls%>%
  slice(-(1:3))%>%
  drop_na()
```

*Creating a dataset of international goals*
```{r}
intgls <- html_table(tables.html[[8]], fill = TRUE) %>% as_tibble()
```

*Creating a dataset of Messi International Goals.*
```{r}
messiintgls <- intgls  %>%
  select(X1,X2,X3,X4,X5,X6,X7,X8)%>%
  slice(3:19)
messiintgls <- messiintgls %>%
  rename(NationalTeam= "X1", Year = "X2", CompApps= "X3", CompGoals = "X4", FrndApps = "X5", FrndGoals = "X6",TotalApps = "X7", TotalGoals = "X8")
messiintgls <- messiintgls%>%
  slice(-(1:2))
```

*Creating a dataset of Ronaldo International Goals.*
```{r}
crisintgls <- intgls  %>%
  select(X1,X2,X3,X4,X5,X6,X7,X8)%>%
  slice(23:41)
crisintgls <- crisintgls %>%
  rename(NationalTeam= "X1", Year = "X2", CompApps= "X3", CompGoals = "X4", FrndApps = "X5", FrndGoals = "X6",TotalApps = "X7", TotalGoals = "X8")
crisintgls <- crisintgls%>%
  slice(-(1:2))
```

```{r}
urlCalendar <- "https://messivsronaldo.net/calendar-year-stats/"
pageCalendar <- read_html(urlCalendar)
```

```{r}
div.html <- html_nodes(pageCalendar, "ul")
str(div.html)
```

```{r}
messi <- html_nodes(pageCalendar, ".messi.stats")
ronaldo <- html_nodes(pageCalendar, ".ronaldo.stats")
```

```{r}
messiStats <- tibble(
  apps = messi %>% html_node(".apps") %>% html_text(),
  assists = messi %>% html_node(".assists") %>% html_text(),
  goals = messi %>% html_node(".goals .num") %>% html_text()
)
```

```{r}
ronaldoStats <- tibble(
  apps = ronaldo %>% html_node(".apps") %>% html_text(),
  assists = ronaldo %>% html_node(".assists") %>% html_text(),
  goals = ronaldo %>% html_node(".goals .num") %>% html_text()
)
```

```{r}
ClubAndCountryStats <- data.frame(matrix(ncol = 12, nrow = nrow(ronaldoStats)))

x <- c("Messi Country Apps", "Messi Country Goals", "Messi Country Assists", "Messi Club Apps", "Messi Club Goals", "Messi Club Assists", "Ronaldo Country Apps", "Ronaldo Country Goals", "Ronaldo Country Assists", "Ronaldo Club Apps", "Ronaldo Club Goals", "Ronaldo Club Assists")

colnames(ClubAndCountryStats) <- x
```

```{r}
ClubAndCountryStats$`Messi Country Goals` <- 
ClubAndCountryStats$`Messi Country Assists` <- 
ClubAndCountryStats$`Messi Club Goals` <-
ClubAndCountryStats$`Messi Club Assists` <- 
ClubAndCountryStats$`Ronaldo Country Goals` <- 
ClubAndCountryStats$`Ronaldo Country Assists`<- 
ClubAndCountryStats$`Ronaldo Club Goals` <- 
ClubAndCountryStats$`Ronaldo Club Assists` <- 
```
