---
title: "Shiny Graphs"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(tidyr)
library(shiny)
```

*Comparing distributions of different statistics*

*Gathering the dataframe*

```{r}
RonaldoComplete <- read_csv("RonaldoComplete.csv")
```

```{r}
MessiComplete <- read_csv("MessiComplete.csv")
```

```{r}
MessiComplete1 <- MessiComplete %>%
  rename(TotApps = "MTotApps", TotAssists = "MTotAssists", TotGoals = "MTotGoals",ClubApps = "MClubApps",ClubAssists = "MClubAssists",ClubGoals = "MClubGoals",CoApps = "MCoApps",CoAssists = "MCoAssists",CoGoals = "MCoGoals")%>%
  mutate(Player = rep(c("Messi"), nrow(MessiComplete)))
```

```{r}
RonaldoComplete1 <- RonaldoComplete %>%
  rename(TotApps = "RTotApps", TotAssists = "RTotAssists", TotGoals = "RTotGoals",ClubApps = "RClubApps",ClubAssists = "RClubAssists",ClubGoals = "RClubGoals",CoApps = "RCoApps",CoAssists = "RCoAssists",CoGoals = "RCoGoals")%>%
  mutate(Player = rep(c("Ronaldo"), nrow(RonaldoComplete)))
```

```{r}
MessiRonaldoLonger <- rbind(MessiComplete1,RonaldoComplete1) %>%
  select(Year, Player, TotApps,TotAssists,TotGoals,ClubApps,
         ClubAssists,ClubGoals,CoApps,CoAssists,CoGoals)
```

```{r}
write_csv(MessiRonaldoLonger, "MessiRonaldoLonger.csv")
```

```{r}
messiAndRonaldoLaLiga <- read_csv("messiAndRonaldoLaLiga.csv")
messiAndRonaldoUEFA <- read_csv("messiAndRonaldoUEFA.csv")
```

```{r}
inputPanel(
  selectInput("x_2", label = "Type of Stat", 
             choices = c("Total Appearances" ="TotApps",
                         "Total Assists" ="TotAssists",
                         "Total Goals" ="TotGoals",
                         "Club Appearances" ="ClubApps",
                         "Club Assists" ="ClubAssists",
                         "Club Goals" ="ClubGoals",
                         "Country Appearances" ="CoApps",
                         "Country Assists" ="CoAssists",
                         "Country Goals" ="CoGoals"))
)
renderPlot({
  ggplot(MessiRonaldoLonger, aes_string(x = "Year", y = input$x_2, fill = "Player")) + 
    geom_col()+
    facet_wrap(~Player)
})
```

```{r}
fluidPage(
  fluidRow( 
    column(width = 3,   
        wellPanel(                
          # data widget: selecting the variables 
          selectInput("y_5", label = "y-axis Variable:",
             choices = c("Total Appearances" ="TotApps",
                         "Total Assists" ="TotAssists",
                         "Total Goals" ="TotGoals",
                         "Club Appearances" ="ClubApps",
                         "Club Assists" ="ClubAssists",
                         "Club Goals" ="ClubGoals",
                         "Country Appearances" ="CoApps",
                         "Country Assists" ="CoAssists",
                         "Country Goals" ="CoGoals"), 
             selected="TotApps")
        )
      ),
    column(width = 8, 
             plotOutput("gap_plot_5",hover="hover_coord_5")
      )
    ),
  fluidRow(
      column(width = 12, 
             tableOutput("hover_data_5")
      )
  )
)

# render plot
output$gap_plot_5 <- renderPlot({
  ggplot(MessiRonaldoLonger, aes_string(x = "Year", y = input$y_5, color= "Player")) + 
    geom_point() + 
    geom_smooth(se = FALSE) +
    theme(axis.text=element_text(size=16),
          axis.title=element_text(size=16) )
})
## render text for hovered point(s)
output$hover_data_5 <- renderTable({
   nearPoints(MessiRonaldoLonger, input$hover_coord_5)[,1:6]
  })
```

```{r}
#LaLiga
inputPanel(
   selectInput("y_6", label = "y-axis Variable:",
             choices = c("Appearances" = "Appearances",
                         "Goals" = "Goals",
                         "Assists" = "Assists"),
             selected="Appearances")
)
renderPlot({
  ggplot(messiAndRonaldoLaLiga, aes_string(x = "Season", y = input$y_6, fill = "Player")) + 
    geom_col()+
    facet_wrap(~Player)
})
```

```{r}
#LaLiga
inputPanel(
   selectInput("y_7", label = "y-axis Variable:",
             choices = c("Appearances" = "Appearances",
                         "Goals" = "Goals",
                         "Assists" = "Assists"),
             selected="Appearances")
)
renderPlot({
  ggplot(messiAndRonaldoUEFA, aes_string(x = "Season", y = input$y_7, fill = "Player")) + 
    geom_col()+
    facet_wrap(~Player)
})
```

```{r}
ui <- fluidPage(

  # App title ----
  titlePanel("Tabsets"),

  # Sidebar layout with input and output definitions ----
  sidebarLayout(

    # Sidebar panel for inputs ----
    sidebarPanel(

      # Input: Select the random distribution type ----
      radioButtons("dist", "Distribution type:",
                   c("Normal" = "norm",
                     "Uniform" = "unif",
                     "Log-normal" = "lnorm",
                     "Exponential" = "exp")),

      # br() element to introduce extra vertical spacing ----
      br(),

      # Input: Slider for the number of observations to generate ----
      sliderInput("n",
                  "Number of observations:",
                  value = 500,
                  min = 1,
                  max = 1000)

    ),

    # Main panel for displaying outputs ----
    mainPanel(

      # Output: Tabset w/ plot, summary, and table ----
      tabsetPanel(type = "tabs",
                  tabPanel("Plot", plotOutput("plot")),
                  tabPanel("Summary", verbatimTextOutput("summary")),
                  tabPanel("Table", tableOutput("table"))
      )

    )
  )
)
```

```{r}
# Define server logic for random distribution app ----
server <- function(input, output) {

  # Reactive expression to generate the requested distribution ----
  # This is called whenever the inputs change. The output functions
  # defined below then use the value computed from this expression
  d <- reactive({
    dist <- switch(input$dist,
                   norm = rnorm,
                   unif = runif,
                   lnorm = rlnorm,
                   exp = rexp,
                   rnorm)

    dist(input$n)
  })

  # Generate a plot of the data ----
  # Also uses the inputs to build the plot label. Note that the
  # dependencies on the inputs and the data reactive expression are
  # both tracked, and all expressions are called in the sequence
  # implied by the dependency graph.
  output$plot <- renderPlot({
    dist <- input$dist
    n <- input$n

    hist(d(),
         main = paste("r", dist, "(", n, ")", sep = ""),
         col = "#75AADB", border = "white")
  })

  # Generate a summary of the data ----
  output$summary <- renderPrint({
    summary(d())
  })

  # Generate an HTML table view of the data ----
  output$table <- renderTable({
    d()
  })

}
```